name: Validate Terraform and Create Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Fetch all branches
        run: git fetch --all

      - name: Ensure develop is up to date
        run: git pull origin develop

      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Sync feature branch to develop'
          body: 'This is an automated PR to sync changes from feature branch to develop.'
          draft: false

      - name: Merge Pull Request
        if: ${{ success() }}
        run: |
          PR_NUMBER=$(gh pr list --state open --head ${{ github.ref_name }} --json number --jq '.[0].number')
          gh pr merge $PR_NUMBER --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}